package com.nexuslink;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.nexuslink.StepsDao;
import com.nexuslink.RunDao;
import com.nexuslink.UserDao;
import com.nexuslink.TaskStepsDao;
import com.nexuslink.TaskMileagesDao;
import com.nexuslink.HasJoinedRoomsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        StepsDao.createTable(db, ifNotExists);
        RunDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
        TaskStepsDao.createTable(db, ifNotExists);
        TaskMileagesDao.createTable(db, ifNotExists);
        HasJoinedRoomsDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        StepsDao.dropTable(db, ifExists);
        RunDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
        TaskStepsDao.dropTable(db, ifExists);
        TaskMileagesDao.dropTable(db, ifExists);
        HasJoinedRoomsDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(StepsDao.class);
        registerDaoClass(RunDao.class);
        registerDaoClass(UserDao.class);
        registerDaoClass(TaskStepsDao.class);
        registerDaoClass(TaskMileagesDao.class);
        registerDaoClass(HasJoinedRoomsDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
