package com.nexuslink;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nexuslink.Steps;

import com.nexuslink.StepsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stepsDaoConfig;

    private final StepsDao stepsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stepsDaoConfig = daoConfigMap.get(StepsDao.class).clone();
        stepsDaoConfig.initIdentityScope(type);

        stepsDao = new StepsDao(stepsDaoConfig, this);

        registerDao(Steps.class, stepsDao);
    }
    
    public void clear() {
        stepsDaoConfig.getIdentityScope().clear();
    }

    public StepsDao getStepsDao() {
        return stepsDao;
    }

}
