package com.nexuslink;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

<<<<<<< HEAD
import com.nexuslink.Steps;

import com.nexuslink.StepsDao;
=======
import com.nexuslink.User;

import com.nexuslink.UserDao;
>>>>>>> 754fa4f10e2ec1296c2ca4beaa393b94cbeede4b

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

<<<<<<< HEAD
    private final DaoConfig stepsDaoConfig;

    private final StepsDao stepsDao;
=======
    private final DaoConfig userDaoConfig;

    private final UserDao userDao;
>>>>>>> 754fa4f10e2ec1296c2ca4beaa393b94cbeede4b

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

<<<<<<< HEAD
        stepsDaoConfig = daoConfigMap.get(StepsDao.class).clone();
        stepsDaoConfig.initIdentityScope(type);

        stepsDao = new StepsDao(stepsDaoConfig, this);

        registerDao(Steps.class, stepsDao);
    }
    
    public void clear() {
        stepsDaoConfig.getIdentityScope().clear();
    }

    public StepsDao getStepsDao() {
        return stepsDao;
=======
        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);

        registerDao(User.class, userDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
>>>>>>> 754fa4f10e2ec1296c2ca4beaa393b94cbeede4b
    }

}
