package com.nexuslink;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stepsDaoConfig;
    private final DaoConfig runDaoConfig;

    private final StepsDao stepsDao;
    private final RunDao runDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stepsDaoConfig = daoConfigMap.get(StepsDao.class).clone();
        stepsDaoConfig.initIdentityScope(type);

        runDaoConfig = daoConfigMap.get(RunDao.class).clone();
        runDaoConfig.initIdentityScope(type);

        stepsDao = new StepsDao(stepsDaoConfig, this);
        runDao = new RunDao(runDaoConfig, this);

        registerDao(Steps.class, stepsDao);
        registerDao(Run.class, runDao);
    }
    
    public void clear() {
        stepsDaoConfig.getIdentityScope().clear();
        runDaoConfig.getIdentityScope().clear();
    }

    public StepsDao getStepsDao() {
        return stepsDao;
    }

    public RunDao getRunDao() {
        return runDao;
    }

}
