package com.nexuslink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STEPS.
 */
public class Steps {

    private Long id;
    private Integer steps;
    private String currentDate;

    public Steps() {
    }

    public Steps(Long id) {
        this.id = id;
    }

    public Steps(Long id, Integer steps, String currentDate) {
        this.id = id;
        this.steps = steps;
        this.currentDate = currentDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSteps() {
        return steps;
    }

    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    public String getCurrentDate() {
        return currentDate;
    }

    public void setCurrentDate(String currentDate) {
        this.currentDate = currentDate;
    }

}
