package com.nexuslink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STEPS.
 */
public class Steps {

    private Long id;
    private Integer uStep;
    private String date;
    private Boolean hasUpLoad;

    public Steps() {
    }

    public Steps(Long id) {
        this.id = id;
    }

    public Steps(Long id, Integer uStep, String date, Boolean hasUpLoad) {
        this.id = id;
        this.uStep = uStep;
        this.date = date;
        this.hasUpLoad = hasUpLoad;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUStep() {
        return uStep;
    }

    public void setUStep(Integer uStep) {
        this.uStep = uStep;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Boolean getHasUpLoad() {
        return hasUpLoad;
    }

    public void setHasUpLoad(Boolean hasUpLoad) {
        this.hasUpLoad = hasUpLoad;
    }

}
