package com.nexuslink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK_STEPS.
 */
public class TaskSteps {

    private Long id;
    private String TaskStepsName;
    private Integer taskFlag;
    private Integer taskNum;

    public TaskSteps() {
    }

    public TaskSteps(Long id) {
        this.id = id;
    }

    public TaskSteps(Long id, String TaskStepsName, Integer taskFlag, Integer taskNum) {
        this.id = id;
        this.TaskStepsName = TaskStepsName;
        this.taskFlag = taskFlag;
        this.taskNum = taskNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskStepsName() {
        return TaskStepsName;
    }

    public void setTaskStepsName(String TaskStepsName) {
        this.TaskStepsName = TaskStepsName;
    }

    public Integer getTaskFlag() {
        return taskFlag;
    }

    public void setTaskFlag(Integer taskFlag) {
        this.taskFlag = taskFlag;
    }

    public Integer getTaskNum() {
        return taskNum;
    }

    public void setTaskNum(Integer taskNum) {
        this.taskNum = taskNum;
    }

}
