package com.nexuslink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK_MILEAGES.
 */
public class TaskMileages {

    private Long id;
    private String TaskMileagesName;
    private Integer taskFlag;
    private Integer taskNum;

    public TaskMileages() {
    }

    public TaskMileages(Long id) {
        this.id = id;
    }

    public TaskMileages(Long id, String TaskMileagesName, Integer taskFlag, Integer taskNum) {
        this.id = id;
        this.TaskMileagesName = TaskMileagesName;
        this.taskFlag = taskFlag;
        this.taskNum = taskNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskMileagesName() {
        return TaskMileagesName;
    }

    public void setTaskMileagesName(String TaskMileagesName) {
        this.TaskMileagesName = TaskMileagesName;
    }

    public Integer getTaskFlag() {
        return taskFlag;
    }

    public void setTaskFlag(Integer taskFlag) {
        this.taskFlag = taskFlag;
    }

    public Integer getTaskNum() {
        return taskNum;
    }

    public void setTaskNum(Integer taskNum) {
        this.taskNum = taskNum;
    }

}
